services:
  db:
    image: postgres:16-alpine
    container_name: fam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: forte
      POSTGRES_PASSWORD: forte
      POSTGRES_DB: forte_asset_manager
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U forte -d forte_asset_manager']
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fam-api
    working_dir: /app
    environment:
      PORT: 3000
      DATABASE_URL: 'postgresql://forte:forte@db:5432/forte_asset_manager?schema=public'
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c 'test -f prisma/schema.prisma && npx prisma generate || true; npm run start:dev'

volumes:
  dbdata:
